# Generated by Django 5.0.7 on 2024-07-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='coins_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
