# Generated by Django 5.0.7 on 2024-07-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tap', '0002_coins_coins_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='energy_level',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
